Play travis
Otus-DevOps-2018-09/demshin_infra pull request #2
Opened 2018-10-17 19:30 UTC by demshin

# Выполнено ДЗ №3

 - [X] Основное ДЗ
 - [X] Задание со *

## В процессе сделано:
 - реинтеграция travis
 - поправлены url'ы
 - перегенерирован secret для travis 

## Как запустить проект:
 - unable

## Как проверить работоспособность:
 - unable

## PR checklist
 - [X] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2018-10-18 11:27 UTC, hostberg requested changes
Судя по всему не настроена интеграция Travis CI и Slack, не вижу в slack-канале сообщений о билдах.

2018-10-20 18:39 UTC, demshin commented
@hostberg что-то я не могу разобраться, что не так

2018-10-24 09:11 UTC, hostberg commented
Попробуй еще раз проверить интеграцию и обрати внимание на то что раньше настраивалось через .org, после июля через .com. Авторизуйся брайзером на _https://travis-ci.com_, через CLI авторизуйся на .com endpoint'е (`--com`), настрой его дефолтным. Должно быть примерно так:

```
~ # travis whoami
You are hostberg (Matvey Mikhaylov)
~ # travis endpoint
API endpoint: https://api.travis-ci.com/
```

После этого перепроверь токены.

2018-10-27 11:18 UTC, demshin commented
@hostberg заработало, жду аппрува :)

2018-10-29 19:25 UTC, hostberg approved these changes

2018-10-29 19:25 UTC, hostberg commented
Работа принята. 👍

2018-10-30 04:41 UTC, merged